-- Generated by node scripts/backend-setup.js.
-- Run ONCE in a new dedicated Duck Race Supabase project.
-- Includes schema, category configuration, grants and RLS atomically.
begin;

-- schema.sql
-- Run once in a new Supabase project, followed by categories.sql and policies.sql.

create table public.learners (
 id uuid primary key default gen_random_uuid(),
 first_name text not null check (char_length(btrim(first_name)) between 1 and 50),
 surname_initial text not null check (surname_initial ~ '^[A-Z]$'),
 course_or_group text not null check (char_length(btrim(course_or_group)) between 1 and 80),
 active boolean not null default true,
 created_at timestamptz not null default now()
);
create table public.staff (
 id uuid primary key references auth.users(id) on delete restrict,
 name text not null,
 email text not null,
 role text not null default 'staff' check(role in ('staff','admin')),
 active boolean not null default true
);
create table public.award_categories (
 id text primary key, name text not null, description text not null, active boolean not null default true
);
create table public.duck_awards (
 id uuid primary key default gen_random_uuid(),
 learner_id uuid not null references public.learners(id) on delete restrict,
 staff_id uuid not null default auth.uid() references public.staff(id) on delete restrict,
 category text not null references public.award_categories(id) on delete restrict,
 public_message text check(char_length(public_message)<=100),
 awarded_at timestamptz not null default now() check(awarded_at<=now()),
 created_at timestamptz not null default now()
);
create index duck_awards_learner_date on public.duck_awards(learner_id,awarded_at desc);
create index duck_awards_date on public.duck_awards(awarded_at desc);
alter table public.learners enable row level security;
alter table public.staff enable row level security;
alter table public.duck_awards enable row level security;
alter table public.award_categories enable row level security;
-- Locked down even before policies.sql has been run.
revoke all on public.learners, public.staff, public.duck_awards, public.award_categories from anon, authenticated;

-- categories.sql
-- Generated from js/config.js by pnpm build. Run after schema.sql.
-- Removed categories stay as inactive history; never delete referenced categories.

update public.award_categories set active=false;
insert into public.award_categories(id,name,description,active) values
('outstanding-work','Outstanding Work','For work that stands out significantly in quality, ambition or execution.',true),
('above-beyond','Going Above & Beyond','For doing considerably more than was reasonably expected.',true),
('improvement','Brilliant Improvement','For clear and meaningful progress from your previous standard.',true),
('helping','Helping Others','For making a meaningful contribution to another learner’s learning or success.',true),
('professional','Professional Behaviour','For demonstrating particularly strong workplace or professional behaviours.',true),
('resilience','Resilience & Perseverance','For persisting through a genuinely difficult challenge or setback.',true),
('creativity','Creativity & Problem Solving','For particularly effective, innovative or thoughtful problem solving.',true),
('contribution','Contribution to Digital','For making a meaningful positive contribution to the wider Digital Technologies community.',true)
on conflict(id) do update set name=excluded.name,description=excluded.description,active=true;

-- policies.sql
create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to authenticated;
-- Fixed search_path and fully qualified relations avoid object-shadowing attacks.
-- This helper avoids recursive RLS on staff. Browser users cannot create staff rows.
create or replace function private.is_staff(require_admin boolean default false)
returns boolean language sql stable security definer set search_path = '' as $$
 select exists(select 1 from public.staff s where s.id=(select auth.uid()) and s.active
 and (not require_admin or s.role='admin'));
$$;
revoke all on function private.is_staff(boolean) from public, anon;
grant execute on function private.is_staff(boolean) to authenticated;
grant select on public.staff, public.learners, public.award_categories, public.duck_awards to authenticated;
grant insert,update on public.learners to authenticated;
grant insert,delete on public.duck_awards to authenticated;
-- No public direct table access, even to learners. Only the projection RPC below.
create policy staff_self on public.staff for select to authenticated using (id=(select auth.uid()));
create policy learners_read on public.learners for select to authenticated using ((select private.is_staff()));
create policy learners_create on public.learners for insert to authenticated with check ((select private.is_staff(true)));
create policy learners_edit on public.learners for update to authenticated using ((select private.is_staff(true))) with check ((select private.is_staff(true)));
create policy categories_read on public.award_categories for select to authenticated using ((select private.is_staff()));
create policy awards_read on public.duck_awards for select to authenticated using ((select private.is_staff()));
create policy awards_create on public.duck_awards for insert to authenticated with check (
 (select private.is_staff()) and staff_id=(select auth.uid())
 and exists(select 1 from public.learners l where l.id=learner_id and l.active)
 and exists(select 1 from public.award_categories c where c.id=category and c.active)
);
create policy awards_delete on public.duck_awards for delete to authenticated using ((select private.is_staff(true)));
-- Ensure award timestamps cannot be forged by a browser client. Historic imports
-- are permitted only from trusted database/service-role tooling.
create or replace function private.stamp_award() returns trigger
language plpgsql set search_path='' as $$
begin
 if current_user in ('authenticated','anon') then
   new.awarded_at=now(); new.created_at=now(); new.staff_id=auth.uid();
 end if;
 return new;
end;
$$;
revoke all on function private.stamp_award() from public, anon, authenticated;
create trigger stamp_award before insert on public.duck_awards for each row execute function private.stamp_award();

-- Admin-only atomic removal keeps the foreign-key restriction for every other caller.
create or replace function public.delete_learner(target_id uuid)
returns boolean language plpgsql security definer set search_path='' as $$
declare removed uuid;
begin
 if not private.is_staff(true) then raise insufficient_privilege; end if;
 delete from public.duck_awards where learner_id=target_id;
 delete from public.learners where id=target_id returning id into removed;
 return removed is not null;
end;
$$;
revoke all on function public.delete_learner(uuid) from public, anon;
grant execute on function public.delete_learner(uuid) to authenticated;

-- The ONLY anonymous data endpoint. Returns course/group as the public lane tagline,
-- but never staff identity,
-- inactive learners or awards outside the requested season. Totals are aggregates.
create or replace function public.public_race(season_start date, season_end date, feed_limit integer default 12)
returns jsonb language plpgsql stable security definer set search_path='' as $$
declare result jsonb;
begin
 if season_end<=season_start or season_end-season_start>370 then
   raise exception 'Invalid academic season';
 end if;
 with eligible as (
   select a.id,a.learner_id,a.category,a.public_message,a.awarded_at,
          l.first_name || ' ' || l.surname_initial || '.' as name,
          l.course_or_group as course
   from public.duck_awards a join public.learners l on l.id=a.learner_id
   where l.active and a.awarded_at >= (season_start::timestamp at time zone 'Europe/London')
     and a.awarded_at < (season_end::timestamp at time zone 'Europe/London')
     and a.awarded_at<=now()
 ), overall as (
   select learner_id as id,name,course,count(*)::integer as total from eligible group by learner_id,name,course
 ), monthly as (
   select learner_id as id,name,course,count(*)::integer as total from eligible
   where date_trunc('month',awarded_at at time zone 'Europe/London')=date_trunc('month',now() at time zone 'Europe/London')
   group by learner_id,name,course
 ), feed as (
   select id,name,category,public_message,awarded_at from eligible
   order by awarded_at desc,id limit greatest(1,least(coalesce(feed_limit,12),50))
 ) select jsonb_build_object(
   'overall',coalesce((select jsonb_agg(to_jsonb(o) order by total desc,name,id) from overall o),'[]'::jsonb),
   'monthly',coalesce((select jsonb_agg(to_jsonb(m) order by total desc,name,id) from monthly m),'[]'::jsonb),
   'total',(select count(*) from eligible),
   'feed',coalesce((select jsonb_agg(to_jsonb(f) order by awarded_at desc,id) from feed f),'[]'::jsonb)
 ) into result;
 return result;
end;
$$;
revoke all on function public.public_race(date,date,integer) from public;
grant execute on function public.public_race(date,date,integer) to anon, authenticated;

notify pgrst, 'reload schema';
commit;
