import {config,categories,category} from './config.js';
import {isDemo,db,staffProfile,staffData,awardDuck,deleteAward,saveLearner,manageStaff} from './data.js';
import {escapeHtml as e,learnerName,dateKey} from './domain.js';
const $=s=>document.querySelector(s);let profile,data,staff=[],selectedDelete,pendingAwardId;
const notice=(message,success=false)=>{const el=$('#notice');el.textContent=message;el.classList.toggle('success',success);el.hidden=false;el.scrollIntoView({behavior:'smooth',block:'nearest'});};
const options=categories.map(c=>`<option value="${c.id}">${e(c.name)}</option>`).join('');
$('#category').insertAdjacentHTML('beforeend',options);$('#filter-category').insertAdjacentHTML('beforeend',options);$('#staff-principle').textContent=config.text.principle;
$('#demo-entry').hidden=!isDemo;$('#login-form').hidden=isDemo;
if(isDemo){$('.login-card h1').innerHTML='Try a little recognition<span>.</span>';$('.login-card .subtle').textContent='Explore the award and management workflow with fictional learners.';}
function renderLearnerOptions(){const query=$('#learner-search').value.toLowerCase().trim(),current=$('#learner').value;
  const learners=data.learners.filter(l=>l.active&&`${learnerName(l)} ${l.course_or_group}`.toLowerCase().includes(query));
  $('#learner').innerHTML=learners.map(l=>`<option value="${e(l.id)}">${e(learnerName(l))} · ${e(l.course_or_group)}</option>`).join('');$('#learner').value=learners.some(l=>l.id===current)?current:'';
  $('#learner-help').textContent=learners.length?'Search, then select a learner below.':'No matching active learners.';
}
function renderAwards(){
  const query=$('#award-search').value.trim().toLowerCase(),learner=$('#filter-learner').value,cat=$('#filter-category').value,from=$('#filter-from').value,to=$('#filter-to').value;
  const rows=data.awards.map(a=>({...a,learner:data.learners.find(l=>l.id===a.learner_id)})).filter(a=>a.learner).filter(a=>(!query||`${learnerName(a.learner)} ${a.public_message||''}`.toLowerCase().includes(query))&&(!learner||a.learner_id===learner)&&(!cat||a.category===cat)&&(!from||dateKey(a.awarded_at)>=from)&&(!to||dateKey(a.awarded_at)<=to)).sort((a,b)=>new Date(b.awarded_at)-new Date(a.awarded_at));
  $('#award-count').textContent=`${rows.length} awards`;
  $('#award-records').innerHTML=rows.map(a=>`<article class="record"><div><h3>${e(learnerName(a.learner))} <span class="yellow">+1 🦆</span></h3><small>${e(category(a.category).name)} · ${e(new Date(a.awarded_at).toLocaleString('en-GB',{timeZone:config.timeZone,dateStyle:'medium',timeStyle:'short'}))}</small>${a.public_message?`<p>${e(a.public_message)}</p>`:''}</div>${profile.role==='admin'?`<button class="secondary" data-delete="${e(a.id)}" aria-label="Remove award for ${e(learnerName(a.learner))}">Remove</button>`:''}</article>`).join('')||'<p class="empty">No awards match these filters.</p>';
}
function renderLearners(){const query=$('#manage-search').value.trim().toLowerCase();$('#learner-records').innerHTML=data.learners.filter(l=>`${learnerName(l)} ${l.course_or_group}`.toLowerCase().includes(query)).map(l=>`<article class="record ${l.active?'':'inactive'}"><div><h3>${e(learnerName(l))}</h3><p>${e(l.course_or_group)} · ${l.active?'Active':'Inactive'}</p></div>${profile.role==='admin'?`<button class="secondary" data-edit="${e(l.id)}">Edit</button>`:''}</article>`).join('')||'<p class="empty">No learners found.</p>';}
function renderStaff(){$('#staff-records').innerHTML=staff.map(s=>`<article class="record ${s.active?'':'inactive'}"><div><h3>${e(s.name)} ${s.id===profile.id?'<span class="staff-self">(you)</span>':''}</h3><p>${e(s.email)}</p><span class="staff-role">${e(s.role)} · ${e(s.setup_status||'Active')}</span></div><div class="staff-record-actions"><label><input type="checkbox" data-staff-active="${e(s.id)}" ${s.active?'checked':''} ${s.id===profile.id?'disabled':''}> Active</label>${s.can_remove_pending?`<button class="secondary" type="button" data-remove-pending="${e(s.id)}">Remove invite</button>`:''}</div></article>`).join('')||'<p class="empty">No staff accounts found.</p>';}
async function loadStaff(){if(profile?.role!=='admin'||isDemo)return;$('#staff-records').innerHTML='<p class="staff-loading">Loading staff…</p>';staff=(await manageStaff('list')).staff||[];renderStaff();}
async function load(){data=await staffData();renderLearnerOptions();const filter=$('#filter-learner'),current=filter.value;filter.innerHTML='<option value="">All learners</option>'+data.learners.map(l=>`<option value="${e(l.id)}">${e(learnerName(l))} · ${e(l.course_or_group)}</option>`).join('');filter.value=current;renderAwards();renderLearners();}
async function enter(p){profile=p;await load();$('#login-panel').hidden=true;$('#workspace').hidden=false;$('#staff-greeting').textContent=`${isDemo?'DEMO · ':''}${profile.name} · ${profile.role==='admin'?'ADMINISTRATOR':'STAFF'}`;$('#add-learner').hidden=profile.role!=='admin';$('#staff-tab').hidden=isDemo||profile.role!=='admin';if(isDemo)notice('Demo mode — fictional data, saved only in this browser. Open the public race in another tab to see your changes.');}
$('#enter-demo').onclick=()=>enter({id:'demo-staff',name:'Demo staff',role:'admin'}).catch(err=>notice(err.message));
$('#login-form').onsubmit=async event=>{event.preventDefault();const btn=event.submitter;btn.disabled=true;try{const s=await db();const {error}=await s.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error)throw error;const p=await staffProfile();if(!p){await s.auth.signOut();throw new Error('This account does not have active staff access. Contact your department administrator.');}$('#password').value='';$('#notice').hidden=true;await enter(p);}catch(err){notice(err.message);}finally{btn.disabled=false;}};
$('#sign-out').onclick=async()=>{try{if(!isDemo){const {error}=await (await db()).auth.signOut();if(error)throw error;}location.reload();}catch(err){notice(err.message);}};
document.querySelectorAll('[data-panel]').forEach(btn=>btn.onclick=async()=>{document.querySelectorAll('.tool-panel').forEach(p=>p.hidden=p.id!==btn.dataset.panel);document.querySelectorAll('[data-panel]').forEach(b=>b.classList.toggle('active',b===btn));try{if(btn.dataset.panel==='staff-panel')await loadStaff();else await load();}catch(err){notice(err.message);}});
$('#learner-search').oninput=renderLearnerOptions;$('#category').onchange=()=>$('#category-description').textContent=category($('#category').value).description||'Recognise a moment that stands out.';
$('#message').oninput=()=>$('#message-count').textContent=`${$('#message').value.length} / 100`;
$('#award-form').addEventListener('input',()=>pendingAwardId=null);
$('#award-form').onsubmit=async event=>{event.preventDefault();const btn=$('#award-submit'),learner=data.learners.find(l=>l.id===$('#learner').value);if(!learner)return;btn.disabled=true;pendingAwardId??=crypto.randomUUID();let saved=false;try{await awardDuck(learner.id,$('#category').value,$('#message').value,profile.id,pendingAwardId);saved=true;pendingAwardId=null;$('#award-form').reset();$('#message-count').textContent='0 / 100';$('#category-description').textContent='Recognise a moment that stands out.';notice(`🦆 Duck awarded to ${learnerName(learner)}!`,true);await load();$('#learner-search').focus();}catch(err){notice(saved?`Duck awarded to ${learnerName(learner)}, but the staff list could not refresh. Reload to see the updated records.`:`Could not confirm the award: ${err.message}. You can retry safely without changing the form.`);}finally{btn.disabled=false;}};
for(const id of ['award-search','filter-learner','filter-category','filter-from','filter-to'])$('#'+id).addEventListener('input',renderAwards);
$('#manage-search').oninput=renderLearners;
$('#award-records').onclick=event=>{const id=event.target.closest('[data-delete]')?.dataset.delete;if(!id)return;selectedDelete=id;const a=data.awards.find(a=>a.id===id),l=data.learners.find(l=>l.id===a.learner_id);$('#delete-description').textContent=`Remove ${learnerName(l)}’s duck for ${category(a.category).name}?`;$('#delete-error').textContent='';$('#delete-dialog').showModal();};
$('#cancel-delete').onclick=()=>$('#delete-dialog').close();$('#confirm-delete').onclick=async()=>{const btn=$('#confirm-delete');btn.disabled=true;try{await deleteAward(selectedDelete);$('#delete-dialog').close();notice('Duck removed. The race totals will update.',true);await load();}catch(err){$('#delete-error').textContent=err.message;}finally{btn.disabled=false;}};
function editLearner(id){const l=data.learners.find(l=>l.id===id);$('#learner-form').reset();$('#edit-id').value=l?.id||'';$('#first-name').value=l?.first_name||'';$('#surname-initial').value=l?.surname_initial||'';$('#group').value=l?.course_or_group||'';$('#learner-active').checked=l?.active??true;$('#learner-dialog-title').textContent=l?'Edit learner':'Add learner';$('#learner-error').textContent='';$('#learner-dialog').showModal();}
$('#add-learner').onclick=()=>editLearner();$('#close-learner').onclick=()=>$('#learner-dialog').close();$('#learner-records').onclick=event=>{const id=event.target.closest('[data-edit]')?.dataset.edit;if(id)editLearner(id);};
$('#learner-form').onsubmit=async event=>{event.preventDefault();const btn=event.submitter;btn.disabled=true;try{const l={first_name:$('#first-name').value.trim(),surname_initial:$('#surname-initial').value.trim().toUpperCase(),course_or_group:$('#group').value.trim(),active:$('#learner-active').checked};if(!l.first_name||!l.course_or_group)throw new Error('Enter a first name and course / group.');if($('#edit-id').value)l.id=$('#edit-id').value;await saveLearner(l);$('#learner-dialog').close();notice('Learner saved.',true);await load();}catch(err){$('#learner-error').textContent=err.message;}finally{btn.disabled=false;}};
$('#staff-invite-form').onsubmit=async event=>{event.preventDefault();const btn=event.submitter;btn.disabled=true;$('#staff-invite-error').textContent='';try{const result=await manageStaff('invite',{name:$('#staff-name').value.trim(),email:$('#staff-email').value.trim().toLowerCase()});event.target.reset();notice(`Invite sent to ${result.staff.email}.`,true);await loadStaff();}catch(err){$('#staff-invite-error').textContent=err.message;}finally{btn.disabled=false;}};
$('#refresh-staff').onclick=()=>loadStaff().catch(err=>notice(err.message));
$('#staff-records').onchange=async event=>{const input=event.target.closest('[data-staff-active]');if(!input)return;input.disabled=true;try{await manageStaff('set-active',{staffId:input.dataset.staffActive,active:input.checked});notice('Staff access updated.',true);await loadStaff();}catch(err){input.checked=!input.checked;notice(err.message);}finally{input.disabled=false;}};
$('#staff-records').onclick=async event=>{const btn=event.target.closest('[data-remove-pending]');if(!btn)return;btn.disabled=true;try{await manageStaff('remove-pending',{staffId:btn.dataset.removePending});notice('Pending invitation removed. You can invite that address again.',true);await loadStaff();}catch(err){notice(err.message);}finally{btn.disabled=false;}};
$('#invite-password-form').onsubmit=async event=>{event.preventDefault();const btn=event.submitter,password=$('#invite-password').value;if(password!==$('#invite-password-confirm').value){notice('Those passwords do not match.');return;}btn.disabled=true;try{const {error}=await (await db()).auth.updateUser({password,data:{duck_setup_complete:true}});if(error)throw error;notice('Password set. Your staff account is ready.',true);const p=await staffProfile();if(!p)throw new Error('Your invitation is valid, but staff access is not active. Contact your department administrator.');await enter(p);}catch(err){notice(err.message);}finally{btn.disabled=false;}};
if(!isDemo){try{const s=await db();s.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'){profile=null;data=null;$('#workspace').hidden=true;$('#login-panel').hidden=false;document.querySelectorAll('dialog[open]').forEach(d=>d.close());}});if(s.auth.acceptInviteFromUrl()){$('#login-form').hidden=true;$('#invite-password-form').hidden=false;$('#access-note').hidden=true;$('.login-card h1').innerHTML='Set your password<span>.</span>';}else{const p=await staffProfile();if(p)await enter(p);}}catch(err){notice(err.message);}}
