import {readFile,writeFile} from 'node:fs/promises';
import './categories.js';

// One transaction prevents a partially installed or partially secured backend.
const names=['schema.sql','categories.sql','policies.sql'];
const sections=await Promise.all(names.map(async name=>{
  const sql=await readFile(new URL(`../supabase/${name}`,import.meta.url),'utf8');
  return `-- ${name}\n${sql.replace(/^\s*(begin|commit);\s*$/gmi,'').trim()}`;
}));
await writeFile(new URL('../supabase/install.sql',import.meta.url),
  `-- Generated by node scripts/backend-setup.js.\n-- Run ONCE in a new dedicated Duck Race Supabase project.\n-- Includes schema, category configuration, grants and RLS atomically.\nbegin;\n\n${sections.join('\n\n')}\n\nnotify pgrst, 'reload schema';\ncommit;\n`);
console.log('Created supabase/install.sql: atomic backend installation.');
